### ISSUE TITLE
Fix  distance calculation (remove animationDistanceCompensation)

### ISSUE THREAD

**Issue by bnayae** [weknow-network/wk-pkg-carousel#1]
The animation is jumpy at the end when having a `margin` at the children's level.
The `animationDistanceCompensation` from `IWCarouselProps` was added to compensate. This prop should be removed after fixing the calculation.
Correct the distance calculation to take `margin` into account.

**Comment by alexeagleson** [comment]
Issue should be fixed with https://github.com/weknow-network/wk-pkg-carousel/commit/7f281dcf873c2721e09961b3c19345f6040a4e76
